# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b92tkCo8bemPxBrQAiECmJOAorQn_ueI
"""

!pip install aiogram nest_asyncio transformers torch accelerate pypdf2 -q

import asyncio
import logging
import torch
import random
import time
import PyPDF2
import nest_asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
from aiogram.types import InlineKeyboardButton, Message
from aiogram.utils.keyboard import InlineKeyboardBuilder
from aiogram.enums.parse_mode import ParseMode
from transformers import AutoTokenizer, AutoModelForCausalLM
import warnings

warnings.filterwarnings('ignore')

nest_asyncio.apply()

BOT_TOKEN = "8562178784:AAFTAuXv9vkLzz647N7O_UdOkR0ViUAZ5xE"
HF_TOKEN = "Напишите свой токен"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

bot = Bot(token=BOT_TOKEN)
dp = Dispatcher()

# База данных горячих клавиш
HOTKEYS_DB = {
    "Моделирование": {
        "E": "экструдирование граней",
        "G": "перемещение объекта",
        "S": "масштабирование объекта",
        "R": "поворачивание объекта",
        "I": "создание новой грани внутри выделенной",
        "Ctrl+R": "сглаживание объекта",
        "M": "объдинение вершин",
        "Shift+A": "создание нового объекта",
        "A": "выделение всего",
        "Alt+E": "выдавливание по нормали",
        "Ctrl+B": "создание фаски на выделенных рёбрах",
        "K": "активирование ножа для резки рёбер",
        "X": "удаление выделенного",
        "Shift+D": "создание независимого дубликата объекта",
        "P": "отделение выделенной геометрии в отдельный объект",
        "Alt+D": "создание зависимого дубликата объекта"
    },
    "Текстурирование": {
        "Shift+F3": "открытие редактора шейдеров",
        "Shift+A": "добавление текстурного узла",
        "Shift+F12": "переключение в texture paint",
        "Ctrl+G": "создание группы из узлов",
        "Ctrl+T": "добавление текстурных координат и маппинга",
        "Ctrl+D": "дублирование узла",
        "Ctrl+Shift+T": "автоматическая загрузка pbr-текстур",
        "N": "открытие боковой панели (настройки)",
        "Tab": "вход в группу узлов",
        "X": "удаление выделенных узлов"
    },
    "Скульптинг": {
        "B": "активация кисти",
        "F": "изменение размера кисти",
        "Shift+F": "изменение интенсивности кисти",
        "S": "активация кисти для рисования маски",
        "Alt+M": "очистка всех нарисованных масок",
        "R": "включение воксельного ремеша",
        "Shift+R": "изменение разрешения вокселя",
        "Ctrl+Alt+M": "показать или скрыть маску",
        "G": "активация кисти захвата (grab)",
        "Ctrl": "временное инвентирование действия кисти"
    },
    "UV-развёртка": {
        "U": "развертка uv",
        "Ctrl+E": "маркировка швов",
        "Ctrl+V": "слияние uv вершин",
        "Alt+O": "загрузка uv изображения",
        "V": "сшивание uv швов",
        "Y": "разделение островов uv по выделенным рёбрам",
        "Ctrl+Alt+P": "упаковка uv острова",
        "Ctrl+P": "прилипание uv вершин (проксима)",
        "N": "открытие боковой панели uv редактора",
        "L": "выделение uv островов"
    },
    "Риггинг": {
        "Shift+A": "добавление кости",
        "E": "экструдирование кости",
        "F": "соединение костей",
        "F2": "переименование кости",
        "Ctrl+Tab": "переключение режимов арматуры",
        "Alt+G": "сбрасывание позы кости",
        "Ctrl+Shift+C": "добавление ограничителя кости",
        "Shift+G": "выделение иерархии кости",
        "Alt+Z": "отображение кости как проволочной сетки",
        "Ctrl+P": "установка автоматических весов кости"
    },
    "Анимация": {
        "I": "вставка ключевого кадра",
        "Alt+I": "очистка ключевых кадров",
        "Space": "воспроизведение анимации",
        "Shift+D": "дублирование ключевого кадра",
        "Alt+O": "сглаживание кривых анимации",
        "Shift+I": "вставка пустого ключевого кадра",
        "Ctrl+Alt+L": "зацикливание анимацию",
        "A": "выделение всех ключевых кадров",
        "Ctrl+Space": "вставка автоматических ключей",
        "Shift+F6": "открытие редактора кривых"
    }
}

# Загрузка LLM
start_load = time.time()

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name, token=HF_TOKEN, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    token=HF_TOKEN,
    trust_remote_code=True,
    torch_dtype=torch.float16,
    device_map="auto"
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(f"Модель загружена за {time.time() - start_load:.1f} сек\n")

# Хранилище сессий
user_sessions = {}

def generate_question_with_llm(action_description, hotkey):
    """Генерирует один вопрос через LLM"""
    prompt = f"""Напиши вопрос о горячей клавише Blender.

Действие: {action_description}
Клавиша: {hotkey}

ПРАВИЛА:
1. В вопросе НЕ ДОЛЖНО БЫТЬ самой клавиши {hotkey}
2. Вопрос должен быть на русском языке
3. Используй правильный падеж для действия
4. Напиши только вопрос, ничего больше

Вопрос:"""

    inputs = tokenizer(prompt, return_tensors="pt", max_length=500, truncation=True).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=80,
            temperature=0.7,
            do_sample=True,
            top_p=0.9,
            pad_token_id=tokenizer.pad_token_id
        )

    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    question = full_response.replace(prompt, "").strip()
    question = question.split('\n')[0].strip()

    if "?" in question:
        question = question.split("?")[0] + "?"

    if hotkey in question:
        question = question.replace(hotkey, "").strip()

    if not question.endswith('?'):
        question += "?"

    return question

def get_next_question(topic, asked_keys):
    """
    Получает следующий вопрос, исключая повторения
    """
    if topic not in HOTKEYS_DB:
        return None, None, None

    all_keys = list(HOTKEYS_DB[topic].keys())
    available_keys = [k for k in all_keys if k not in asked_keys]

    if not available_keys:
        available_keys = all_keys
        asked_keys.clear()

    hotkey = random.choice(available_keys)
    action_description = HOTKEYS_DB[topic][hotkey]
    question = generate_question_with_llm(action_description, hotkey)

    return question, hotkey, action_description

# Создание клавиатуры с разделами
def topics_keyboard():
    builder = InlineKeyboardBuilder()
    topics = list(HOTKEYS_DB.keys())
    for topic in topics:
        builder.add(InlineKeyboardButton(text=topic, callback_data=f"topic_{topic}"))
    builder.adjust(2)
    return builder.as_markup()

# Клавиатура с действиями после ответа
def after_answer_keyboard():
    builder = InlineKeyboardBuilder()
    builder.add(InlineKeyboardButton(text="(=⚈ᆽ⚈=)  Ещё вопрос по этой теме", callback_data="same_topic"))
    builder.add(InlineKeyboardButton(text="(=✿ܫ✿=)  Другая тема", callback_data="change_topic"))
    builder.add(InlineKeyboardButton(text="(=✪ᆺ✪=)  Завершить тренировку", callback_data="end_training"))
    builder.adjust(1)
    return builder.as_markup()

# Команда /start
@dp.message(Command("start"))
async def cmd_start(message: Message):
    chat_id = message.chat.id

    user_sessions[chat_id] = {
        "current_topic": None,
        "asked_keys": [],
        "current_hotkey": None,
        "current_question": None,
        "current_action": None,
        "statistics": {}
    }

    welcome_text = (
        "ฅ(ﾐ⚈ᆽ⚈ﾐ)ฅ *Blender Hotkeys Helper*\n\n"
        "Привет! Я помогу тебе выучить горячие клавиши Blender.\n\n"
        "*Как это работает:*\n"
        "1. Выбери раздел\n"
        "2. Я задам вопрос о горячей клавише\n"
        "3. Напиши ответ (например: E, Ctrl+R, Shift+A)\n"
        "4. После ответа выбери следующее действие\n\n"
        "*Выбери раздел для тренировки:*"
    )

    await message.answer(welcome_text, parse_mode=ParseMode.MARKDOWN, reply_markup=topics_keyboard())

# Команда /help
@dp.message(Command("help"))
async def cmd_help(message: Message):
    help_text = (
        "(ﾐ⚈ ﻌ ⚈ﾐ) *Справка*\n\n"
        "*Команды:*\n"
        "/start - Начать тренировку\n"
        "/help - Показать эту справку\n\n"
        "*Как отвечать:*\n"
        "Вводите только горячую клавишу или сочетание\n"
        "Примеры: `E`, `Ctrl+R`, `Shift+A`, `Alt+E`\n\n"
        "*Доступные разделы:*\n"
        "• Моделирование\n"
        "• Текстурирование\n"
        "• Скульптинг\n"
        "• UV-развёртка\n"
        "• Риггинг\n"
        "• Анимация"
    )

    await message.answer(help_text, parse_mode=ParseMode.MARKDOWN)

# Обработка выбора темы
@dp.callback_query(lambda call: call.data.startswith("topic_"))
async def handle_topic(call: types.CallbackQuery):
    chat_id = call.message.chat.id
    topic = call.data.replace("topic_", "")

    if chat_id not in user_sessions:
        user_sessions[chat_id] = {
            "current_topic": None,
            "asked_keys": [],
            "current_hotkey": None,
            "current_question": None,
            "current_action": None,
            "statistics": {}
        }

    user_sessions[chat_id]["current_topic"] = topic
    user_sessions[chat_id]["asked_keys"] = []

    await call.answer(f"Выбрано: {topic}")

    try:
        await call.message.delete()
    except:
        pass

    loading_msg = await call.message.answer("🐾  Нейросеть генерирует вопрос, на это требуется время...")
    await ask_next_question(chat_id, loading_msg.message_id)

async def ask_next_question(chat_id: int, loading_msg_id: int = None):
    session = user_sessions.get(chat_id)
    if not session or not session["current_topic"]:
        await bot.send_message(chat_id, "Ошибка. Пожалуйста, начните заново с /start")
        return

    topic = session["current_topic"]
    asked_keys = session["asked_keys"]

    question, hotkey, action_description = await asyncio.to_thread(get_next_question, topic, asked_keys)

    session["asked_keys"].append(hotkey)
    session["current_question"] = question
    session["current_hotkey"] = hotkey
    session["current_action"] = action_description

    if loading_msg_id:
        try:
            await bot.delete_message(chat_id, loading_msg_id)
        except:
            pass

    await bot.send_message(
        chat_id,
        f"*{question}*\n\nฅ^•⩊•^ฅ Напиши свой ответ:",
        parse_mode=ParseMode.MARKDOWN
    )

@dp.message()
async def handle_answer(message: Message):
    chat_id = message.chat.id

    if message.text and message.text.startswith('/'):
        return

    if chat_id not in user_sessions or not user_sessions[chat_id]["current_topic"]:
        await message.answer("Пожалуйста, начните с команды /start")
        return

    session = user_sessions[chat_id]

    if not session["current_hotkey"]:
        await message.answer("Сначала выберите тему с помощью /start")
        return

    user_answer = message.text.strip().lower().replace(" ", "")
    expected_answer = session["current_hotkey"].lower().replace(" ", "")
    is_correct = user_answer == expected_answer

    current_topic = session["current_topic"]
    if current_topic not in session["statistics"]:
        session["statistics"][current_topic] = {"total": 0, "correct": 0}

    session["statistics"][current_topic]["total"] += 1
    if is_correct:
        session["statistics"][current_topic]["correct"] += 1

    if is_correct:
        result_text = (
            f"😻 *Правильно!* Отлично!\n\n"
            f"Вопрос: {session['current_question']}\n"
            f"Ваш ответ: `{message.text}`"
        )
    else:
        result_text = (
            f"🙀 *Неправильно*\n\n"
            f"Вопрос: {session['current_question']}\n"
            f"Ваш ответ: `{message.text}`\n"
            f"Правильный ответ: `{session['current_hotkey']}`\n\n"
            f"😿 Запомните эту комбинацию!"
        )

    await message.answer(result_text, parse_mode=ParseMode.MARKDOWN)
    await message.answer(
        "(ﾐ◕ᆽ<ﾐ)  *Что дальше?*",
        parse_mode=ParseMode.MARKDOWN,
        reply_markup=after_answer_keyboard()
    )

@dp.callback_query(lambda call: call.data in ["same_topic", "change_topic", "end_training"])
async def handle_after_answer(call: types.CallbackQuery):
    chat_id = call.message.chat.id
    action = call.data

    if action == "same_topic":
        await call.answer("Задаю новый вопрос...")
        await call.message.delete()
        loading_msg = await call.message.answer("🐾  Нейросеть генерирует новый вопрос, на это требуется время...")
        await ask_next_question(chat_id, loading_msg.message_id)

    elif action == "change_topic":
        await call.answer("Выберите новую тему")
        await call.message.edit_text(
            "*Выберите раздел:*",
            parse_mode=ParseMode.MARKDOWN,
            reply_markup=topics_keyboard()
        )

    elif action == "end_training":
        await call.answer("Тренировка завершена")

        session = user_sessions[chat_id]
        statistics = session.get("statistics", {})

        if statistics:
            stats_text = "😼 *Статистика правильных ответов:*\n\n"
            total_all = 0
            correct_all = 0

            for topic, stats in statistics.items():
                total = stats["total"]
                correct = stats["correct"]
                percentage = (correct / total * 100) if total > 0 else 0
                stats_text += f"*{topic}*\n"
                stats_text += f"   😽 {correct}/{total} ({percentage:.1f}%)\n\n"
                total_all += total
                correct_all += correct

            total_percentage = (correct_all / total_all * 100) if total_all > 0 else 0
            stats_text += f"*Итого:*\n"
            stats_text += f"   😻 {correct_all}/{total_all} ({total_percentage:.1f}%)\n"
        else:
            stats_text = "*Статистика:*\nНет отвеченных вопросов за эту сессию.\n"

        end_text = (
            "*Тренировка завершена!*\n\n"
            f"{stats_text}\n"
            "Чтобы начать новую тренировку, используй команду /start"
        )

        await call.message.edit_text(end_text, parse_mode=ParseMode.MARKDOWN)

        user_sessions[chat_id] = {
            "current_topic": None,
            "asked_keys": [],
            "current_hotkey": None,
            "current_question": None,
            "current_action": None,
            "statistics": {}
        }

# Запуск бота
async def main():
    await bot.delete_webhook(drop_pending_updates=True)
    await dp.start_polling(bot)

print("Бот готов к работе!")
print("Напишите /start в Telegram")

asyncio.run(main())
